[package]
name = "program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint=[]
test-sbf=[]

[lib]
crate-type = ["cdylib","lib"]


[dependencies]
borsh = "1.5.1"
solana-program = "2.0.0"
thiserror = "1.0.61"

[dev-dependencies]
solana-program-test = "2.0.0"
solana-sdk = "2.0.0"
